version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build_test_backend:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: runningdinner
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "runningdinner-backend/pom.xml" }} # appends cache key with a hash of pom.xml file
            - dependencies- # fallback in case previous cache key is not found
      - attach_workspace:
          at: runningdinner-backend/src/main/resources
      - run:
          name: Setup application-prod.properties # Not very nice, but sufficient for now
          command: |
            echo "aws.sqs.geocode.url=${PROD_AWS_SQS_GEOCODE_URL}" >> runningdinner-backend/src/main/resources/application-prod.properties

            echo "sendgrid.api.key=${PROD_SENDGRID_API_KEY}" >> runningdinner-backend/src/main/resources/application-prod.properties

            echo 'host.context.url=https://runyourdinner.eu' >> runningdinner-backend/src/main/resources/application-prod.properties

            echo "spring.datasource.password=${PROD_SPRING_DATASOURCE_PASSWORD}" >> runningdinner-backend/src/main/resources/application-prod.properties
            echo "spring.datasource.username=${PROD_SPRING_DATASOURCE_USERNAME}" >> runningdinner-backend/src/main/resources/application-prod.properties
            echo "spring.datasource.url=${PROD_SPRING_DATASOURCE_URL}" >> runningdinner-backend/src/main/resources/application-prod.properties

            echo "spring.flyway.password=${PROD_SPRING_FLYWAY_PASSWORD}" >> runningdinner-backend/src/main/resources/application-prod.properties
            echo "spring.flyway.user=${PROD_SPRING_FLYWAY_USER}" >> runningdinner-backend/src/main/resources/application-prod.properties
            echo "spring.flyway.url=${PROD_SPRING_FLYWAY_URL}" >> runningdinner-backend/src/main/resources/application-prod.properties
      - run:
          name: Build + Test
          command: |
            cd runningdinner-backend
            ./mvnw package
      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "runningdinner-backend/pom.xml" }}
      - run: cp runningdinner-backend/infrastructure/deployment/deploy.sh runningdinner-backend/target/deploy.sh
      - maven/process_test_results:
          test_results_path: runningdinner-backend/target/surefire-reports
      - run: cd runningdinner-backend/target && tar -cvzf runningdinner.tar.gz runningdinner-2.0.0.jar && cd -
      - store_artifacts:
          path: runningdinner-backend/target/runningdinner.tar.gz
      - store_artifacts:
          path: runningdinner-backend/target/deploy.sh
      - persist_to_workspace:
          root: runningdinner-backend/target
          paths:
            - runningdinner.tar.gz
            - deploy.sh

  build_webclient:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "runningdinner-backend/package.json" }}
            - npm-deps-
      - run: cd runningdinner-backend && npm install
      - run:
          name: Build webclient
          command: |
            export GOOGLE_MAPS_KEY_JS=$GOOGLE_MAPS_KEY_JS
            cd runningdinner-backend && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: dependencies-{{ checksum "runningdinner-backend/package.json" }}
      - persist_to_workspace:
          root: runningdinner-backend/src/main/resources
          paths:
            - static

  deploy_runningdinner_app:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: runningdinner-backend/target
      - add_ssh_keys:
          fingerprints:
            - "f8:85:06:d1:12:e5:0f:76:e6:dd:30:7b:41:f0:af:5e"
      - run:
          name: Allow SSH Access
          command: |
            export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            runningdinner-backend/infrastructure/deployment/allow-ssh-access.sh
      - run: touch ssh-access-granted.txt
      - run:
          name: Upload artifacts
          command: |
            chmod +x runningdinner-backend/target/deploy.sh
            scp runningdinner-backend/target/deploy.sh runningdinner-backend/target/runningdinner.tar.gz $SSH_USER@$SSH_HOST:~/upload
      - run:
          name: Run Deploy script
          command: |
            ssh $SSH_USER@$SSH_HOST "./upload/deploy.sh"
      - run:
          name: Check App is healthy
          command: |
            curl -XGET https://runyourdinner.eu/rest/masterdataservice/v1/registrationtypes
      - run:
          name: Remove SSH Access
          command: |
            export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            if [[ -f "ssh-access-granted.txt" ]] ; then
              echo "Removing ssh access..."
              runningdinner-backend/infrastructure/deployment/remove-ssh-access.sh
            else
              echo "Do not remove ssh access due to ssh-access-granted.txt did not exist..."
            fi
          when: always

  deploy_runningdinner_functions:
    docker:
      - image: cimg/node:current
    environment:
      SERVERLESS_ACCESS_KEY: $PROD_SERVERLESS_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "runningdinner-functions/package.json" }}
            - npm-deps-
      - run:
          name: Install serverless framework and all needed dependencies
          command: |
            cd runningdinner-functions
            sudo npm install -g serverless
            npm install
      - run:
          name: Deploy runningdinner-functions lambda(s)
          command: |
            cd runningdinner-functions
            export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            export SERVERLESS_ACCESS_KEY=$PROD_SERVERLESS_ACCESS_KEY

#            echo "Performing serverless login..."
#            serverless login

            echo "GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_KEY_JS}" > secrets.prod.yml
            # I don't know why the encrypt/decrypt does not work... hence use the workaround above for now...
            # serverless decrypt --stage prod --password '${PROD_GEOCODE_SECRETS_PASSWORD}'

            echo "Starting deploy..."
            serverless deploy --stage prod --verbose
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: dependencies-{{ checksum "runningdinner-functions/package.json" }}

workflows:
  build_test_deploy_app:
    jobs:
      - build_webclient:
          context: workspace
      - build_test_backend:
          context: workspace
          requires:
            - build_webclient
      - confirm-app-deployment:
          type: approval
          filters:
            branches:
              only: main
      - deploy_runningdinner_app:
          context: workspace
          requires:
            - build_test_backend
            - confirm-app-deployment
          filters:
            branches:
              only: main

  deploy_functions:
    jobs:
      - confirm-functions-deployment:
          type: approval
          filters:
            branches:
              only: main
      - deploy_runningdinner_functions:
          context: workspace
          requires:
            - confirm-functions-deployment
          filters:
            branches:
              only: main
