
services:

  nginx:
    image: nginx
    container_name: web
    depends_on:
      - runyourdinner
    ports:
      - "80:80"

  runyourdinner:
    image: "clemensstich/runyourdinner:${APP_VERSION}"
    container_name: runyourdinner
    command: ["java", "-jar", "TODO"]
    restart: on-failure
    healthcheck:
      test: curl localhost:8080/runningdinner/health
      interval: 60s
      timeout: "5s"
      start_period: "60s"
      retries: 5
    env_file:
      - aws.env
    volumes:
      - ${HOME}/runningdinner/logs:/${HOME}/runningdinner