version: '3'

services:

  nginx:
    image: nginx
    container_name: web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ../../src/main/resources:/usr/share/nginx/html
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    extra_hosts:
      - "runningdinner-backend:${DOCKER_HOST_IP}"

  postgres:
    image: postgres:9.6.6
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=root


#  sqs:
#    image: softwaremill/elasticmq
#    container_name: sqs
#    ports:
#      - "9324:9324"
#    volumes:
#      - ./elasticmq.conf:/opt/elasticmq.conf

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
#      - DEBUG=${DEBUG-}
      - DEBUG=1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: "verdaccio"
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/conf:/verdaccio/conf"

volumes:
  verdaccio:
    driver: local

  postgres-data:
