version: '3'

services:

  nginx:
    image: nginx
    container_name: web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ../../src/main/resources:/usr/share/nginx/html
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    extra_hosts:
      - "runningdinner-backend:${DOCKER_HOST_IP}"

  postgres:
    image: postgres:12.11
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=root


  sqs:
    image: softwaremill/elasticmq
    container_name: sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: "verdaccio"
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/conf:/verdaccio/conf"

volumes:
  verdaccio:
    driver: local
