version: '3'

services:

  nginx:
    image: nginx
    container_name: web
    network_mode: "host"
    volumes:
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ../../src/main/resources:/usr/share/nginx/html
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem

  postgres:
    image: postgres:9.6.6
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=root


  sqs:
    image: softwaremill/elasticmq
    container_name: sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
