export const CONSTANTS = {

  "REGISTRATION_TYPE": {
    "OPEN": "OPEN",
    "CLOSED": "CLOSED",
    "PUBLIC": "PUBLIC"
  },

  "GENDER": {
    "MALE": "MALE",
    "FEMALE": "FEMALE",
    "UNDEFINED": "UNDEFINED"
  },

  "ASSIGNMENT_TYPE": {
    'NOT_ASSIGNABLE': 'NOT_ASSIGNABLE',
    'ASSIGNED_TO_TEAM': 'ASSIGNED_TO_TEAM',
    'ASSIGNABLE': 'ASSIGNABLE'
  },

  "PARTICIPANT_SELECTION": {
    "ALL": "ALL",
    "ASSIGNED_TO_TEAM": "ASSIGNED_TO_TEAM",
    "NOT_ASSIGNED_TO_TEAM": "NOT_ASSIGNED_TO_TEAM",
    "CUSTOM_SELECTION": "CUSTOM_SELECTION"
  },

  "TEAM_SELECTION": {
    "ALL": "ALL",
    "CUSTOM_SELECTION": "CUSTOM_SELECTION"
  },

  "TEAM_STATUS": {
    "REPLACED": "REPLACED",
    "CANCELLED": "CANCELLED",
  },

  "VALIDATION_ISSUE_CONSTANTS": {
    "TEAM_NO_TEAM_MEMBERS_LEFT": "team_no_team_members_left",
    "PARTICIPANT_ASSINGED_IN_TEAM": "participant_assigned_in_team"
  }
};


