name: Build Backend + Webclient

on:
  push:
  workflow_dispatch:

env:
  DEV_STAGE_BRANCH: develop
  MAIN_STAGE_BRANCH: main

jobs:
  build_backend:
    uses: ./.github/actions/build-backend
    with:
      stageSubdomain: ""
    secrets: inherit

  build_webclient:
    uses: ./.github/actions/build-webclient
    secrets: inherit
