name: Deploy Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  DEV_STAGE_BRANCH: develop
  MAIN_STAGE_BRANCH: main

jobs:
  deploy_backend_ecs:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print env
        run: |
          echo "Env is $AWS_ACCOUNT_ID"
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
